### ISSUE TITLE
How to apply the customized class<darkNotepadTextEdit> in pyqt?

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-dark-notepad#1]
Hi, there. Today I've tried to use the promote function in QtDesigner to make class<QTextEdit> be promoted to class<darkNotepadTextEdit> but with no luck. Then I looked through your source code and found something below:

        self.__textEdit = DarkNotepadTextEdit()
        self.__textEdit.textChanged.connect(self.__setChangedFlag)
        self.__textEdit.textChanged.connect(self.__renewCharsLinesCountInStatusBar)
        self.__textEdit.textChanged.connect(self.__lineWidgetLineCountChanged)
        self.__textEdit.cursorPositionChanged.connect(self.__renewRcInfoInStatusBar)
        self.__textEdit.fileDropped.connect(self.__execOpen)
        self.__textEdit.zoomSignal.connect(self.__zoomByWheel)
        self.__textEdit.cursorOnTop.connect(self.__showMenu)
        self.__textEdit.showInExplorer.connect(self.__showInExplorer)

Does it mean that class<darkNotepadTextEdit> can only be applied by method "addWidget" when the layout exists?

P.S.: 1. How to prevent non-English text input method from sending out signals (even if it is null)?
       2.  My menu actions cannot be set shortcut keys like "Ctrl + S". Is it related to class<QTextEdit> on MainWindow?
       3. Looking forwards to your early reply^^

**Comment by Liskelleo** [comment]
oops, something is missing... Let me try it again...
Hi, there. Today I've tried to use the promote function in QtDesigner to make class"QTextEdit" be promoted as class"darkNotepadTextEdit" but with no luck. Then I looked through your source code and found something below:

    self.__textEdit = DarkNotepadTextEdit()
    self.__textEdit.textChanged.connect(self.__setChangedFlag)
    self.__textEdit.textChanged.connect(self.__renewCharsLinesCountInStatusBar)
    self.__textEdit.textChanged.connect(self.__lineWidgetLineCountChanged)
    self.__textEdit.cursorPositionChanged.connect(self.__renewRcInfoInStatusBar)
    self.__textEdit.fileDropped.connect(self.__execOpen)
    self.__textEdit.zoomSignal.connect(self.__zoomByWheel)
    self.__textEdit.cursorOnTop.connect(self.__showMenu)
    self.__textEdit.showInExplorer.connect(self.__showInExplorer)
Does it mean that class"darkNotepadTextEdit" can only be applied by method "addWidget" when the layout exists?

P.S.: 1. How to prevent non-English text input method from sending out signals (even if it is null)?
2. My menu actions cannot be set shortcut keys like "Ctrl + S". Is it related to class"QTextEdit" on MainWindow?
3. Looking forwards to your early reply^^

**Comment by yjg30737** [comment]
Hello.

**Does it mean that class"darkNotepadTextEdit" can only be applied by method "addWidget" when the layout exists?**

Yes, because it is `QWidget`.

P.S.
**1. How to prevent non-English text input method from sending out signals (even if it is null)?**
I can't quite understand the question because of my bad English skill 😥.  (prevent "method" or "text"?)
But, from what i understand, i assume that you want to **filter** the non-English text.

Well.. i guess you want to use `darkNotepadTextEdit` as your customized widget. Am i right?
Sorry but you can't, because `darkNotepadTextEdit` won't operate as usual since it heavily depends on its parent widget `DarkNotepad`.

Sorry for my alumni answer :(

But i still can help you though. If you have any questions, please don't hesitate to ask. I can even make the customized NotepadTextEdit for you because even i think that needs to be done

**Comment by Liskelleo** [comment]
Thanks for answering that. ^^
Now I've solved two of three questions, the only one left is the issue in P.S.1.
I'm sorry I didn't make myself clear about this. Let me express it again:
Before the user completes the input by using the input method (pictured), although the number of characters displayed in the status bar is 0, a signal will still be transmitted every time a keyboard key is pressed. I want to prevent the signal from sending out until the user completes the input by using the input method.
![image](https://user-images.githubusercontent.com/97718634/209463581-811f0087-f389-4e44-b777-05eb0331fe6f.png)
Btw, merry Christmas. Today's 1225. ^—^

**Comment by yjg30737** [comment]
Good. Happy Christmas, although it is 2 days ago to me

Well i have to say that i've never known what "input method" is until you show it to me. Now at least i know what that is.

Here's the answer: 
So far, i can't find how to make Qt (or PyQt at least) distinguish the usual input from "input method"'s input.

But i have to say sorry for this because i don't have much time;

But i can give you some links, they might be helpful..

https://doc.qt.io/qt-6/qinputmethodevent.html (QInputMethodEvent)

https://learn.microsoft.com/en-us/windows/win32/intl/input-method-manager-messages (Input Method Manager Messages in win32)

Of course this will be not sufficient answer for you, but i guess you might be in a hurry so i have to answer earlier than it should be.

Sorry 😥

If you have any questions(obviosly) don't hesitate to ask bye

**Comment by Liskelleo** [comment]
Ok then. I'll keep learning and trying. Thank you for your help^^
